"""
Pitch to Postgres: Designing and Querying a Relational Database for FIFA World Cup Data
Interpretations of the 30 analytical queries (Milestone 4).

Shared by notebooks/04_queries.ipynb and docs/final_report.md so that the text is written once.
Every statement was checked against the query results on the loaded database.
"""

INTERP = {
"Q01": "Brazil is the most successful team, with 5 titles, 7 finals and 11 top-four finishes. Italy (4 titles) and West Germany (3) follow. Counting West Germany and Germany as one footballing nation would give 4 titles and 13 top-four finishes, so a broadcaster's 'most successful nations' graphic should state which convention it uses.",
"Q02": "Among teams with at least 10 matches, Brazil has the best record (73 wins in 109 matches, 67.0%), followed by Germany and West Germany; Bulgaria won only 3 of 26. Because a shoot-out counts as a draw, these figures follow FIFA's convention. Analysts should keep the minimum-matches filter, since small samples such as Turkey's 10 matches inflate percentages.",
"Q03": "Hosts won 62.7% of their matches against 37.3% for all other teams, with an average goal difference of +0.92 per match. The advantage has shrunk, from 71.9% before 1982 to 54.1% since, so a federation bidding to host can expect a real but smaller boost today.",
"Q04": "CONMEBOL teams have the highest win rate in most decades (about 41-56%), while UEFA teams are steady at 38-47%. CAF and AFC teams went from no wins in the 1930s to about 19-21% in the 2000s and 2010s, which matters in debates on allocating World Cup places. The confederation shown is each team's current one.",
"Q05": "30 teams have never progressed beyond the opening round. Scotland is the most persistent case (8 tournaments, 23 matches), followed by Iran and Tunisia (5 each). For these federations, reaching the second round would be a historic first, which makes this a clear benchmark of progress.",
"Q06": "16 teams have reached the top four without ever winning. The Netherlands stand out, with three lost finals (1974, 1978, 2010) and five top-four finishes; Sweden, Croatia, Czechoslovakia and Hungary have also lost finals.",
"Q07": "Brazil are unbeaten against Sweden in seven World Cup meetings (5 wins, 2 draws), including the 1958 final and the 1994 semi-final. Changing the two names in `params` produces the same history for any pair, which is useful to coaches and broadcasters before a match.",
"Q08": "Uruguay, Italy and Brazil traded the lead in the early years; after 1962 they were tied on two titles each. Brazil took the sole lead in 1970, were caught by Italy in 1982 and by Italy and West Germany in 1990, and have led alone since their fourth title in 1994.",
"Q09": "Brazil (15) and West Germany (10) most often won after conceding the first goal, each turning 45.5% of such matches into wins. Most teams rarely recover; Argentina won only 4 of 29. Scoring first is therefore a strong predictor of the result, a point coaches and in-game analysts can use.",
"Q10": "Miroslav Klose is the all-time top scorer with 16 goals over four tournaments, one ahead of Ronaldo. Just Fontaine's 13 goals all came in one tournament (1958), and six players share eighth place with 10 goals (13 rows in total because ties are kept); Gabriel Batistuta scored 4 of his 10 from penalties.",
"Q11": "In 20 of 21 tournaments the official Golden Boot went to the player or players with the most goals; earlier ties were simply shared (six players in 1962). The exception is 2010: four players scored 5 goals, but the award went to Thomas Müller alone. FIFA broke that tie on a further criterion (assists) that the goals table alone cannot reproduce.",
"Q12": "There have been 52 hat-tricks. Oleg Salenko's five goals against Cameroon (1994) are the record for one match, and six players have scored four; Ernst Wilimowski scored four for Poland in 1938 and still lost 5-6 to Brazil.",
"Q13": "Substitutes scored about 5% of goals in the 1970s, but between 9.6% and 19.3% in every tournament since 2006, peaking at 32 goals (19.3%) in 2014. Benches have become a real attacking weapon, which coaches can plan for.",
"Q14": "Squads have got older: average age rose from 24.9 in 1930 to 27.9 in 2018. Goalkeepers have been the oldest group at every tournament since 1958 (29.6 in 2018), and forwards and midfielders are usually the youngest. Birth dates are missing for 79 squad members, all from 1962 or earlier, and they are left out of the averages.",
"Q15": "Miroslav Klose (24 for Germany) and Paolo Maldini (23 for Italy) have the most appearances for a single team. Lothar Matthäus, the overall record holder with 25, tops neither list because his appearances are split between West Germany and Germany (see validation check V12). This is a direct result of counting historical teams separately.",
"Q16": "34 players appeared for more than one national team. Most reflect states that were renamed or split: West Germany to Germany, and Yugoslavia to Serbia and Montenegro to Serbia (Dejan Stanković played for all three). A few are genuine changes of nationality in the 1930s-1960s, such as Luis Monti (Argentina 1930, Italy 1934) and Ferenc Puskás (Hungary 1954, Spain 1962).",
"Q17": "Scoring peaked at 5.38 goals per match in 1954 and has stayed below 3 since 1962. The low point was 1990 (2.21); the next tournament rose by 0.50 goals per match, the largest increase since 1954, and recent tournaments sit at about 2.6-2.7.",
"Q18": "Three matches share the record winning margin of nine goals; the most emphatic was Hungary's 10-1 win over El Salvador in 1982. The highest-scoring match is Austria 7-5 Switzerland, the 1954 quarter-final (12 goals), and the 1954 tournament supplies several entries in this list.",
"Q19": "Goals become more frequent as a match goes on: 13.1% come in the first 15 minutes, but 18.6% come in minutes 76-90, plus another 2.5% in second-half stoppage time. Coaches can use this to plan fitness and late substitutions, and broadcasters should expect decisive moments late.",
"Q20": "2018, the first World Cup with VAR, had the highest share of goals from penalties (22, 13.0%) and of own goals (12, 7.1%). The average penalty share of all earlier tournaments was 7.1%. Referees' bodies evaluating VAR would see a clear jump in penalties, although one tournament is a small sample.",
"Q21": "Argentina have won the most shoot-outs (4 of 5), and West Germany won all three of theirs, scoring 13 of 14 kicks (92.9%). Among teams with four shoot-outs, England have the lowest conversion (57.9%, one win), and Mexico lost both of theirs, scoring only 2 of 7 kicks. This is useful material for coaches and sports psychologists preparing for shoot-outs.",
"Q22": "Ľuboš Micheľ (Slovakia) showed 8.0 cards per match, 4.5 above the average for all matches since 1970, followed by Howard Webb (6.67) and Arturo Brizio Carter (6.50, with 7 sendings-off). The most lenient referees with at least five matches averaged about 2 cards. Referees' bodies can use such tables to check consistency, although a referee's average also reflects the matches they were given.",
"Q23": "Cards per match rose from 1.63 in 1970 to a peak of 5.52 in 2006, and the moving average shows a steady climb through the 1990s. Since then the figure has fallen to 3.52 in 2018, with only 4 sendings-off. Rule makers would want to explain that drop, for example through refereeing guidance or VAR.",
"Q24": "Knockout matches are more heated. Finals since 1970 average 5.0 cards, and 30.8% of them had a sending-off, against 3.37 cards and 17.1% for group-stage matches. Third-place matches, with less at stake, had no sendings-off at all.",
"Q25": "Argentina have received the most cards since 1970 (123 in 65 matches). Relative to matches played, Ghana (2.92 per match), Chile (2.50) and Cameroon (2.39, with 8 sendings-off) are the most carded. Disciplinary committees and coaches should compare cards per match rather than raw totals, because teams played very different numbers of matches.",
"Q26": "Estadio Azteca has hosted the most World Cup matches (19), including two finals, followed by the Maracanã (15); nine stadiums share tenth place with 9 matches, so the list has 18 rows. Mexican stadiums dominate the list because Mexico hosted twice, in 1970 and 1986, which is relevant for host-bid committees planning to reuse venues.",
"Q27": "Helmut Schön (West Germany) managed the most matches (25) and won 16 of them. Bora Milutinović and Carlos Alberto Parreira each took five different countries to World Cups, and Joachim Löw has the best win rate in this list (70.6%).",
"Q28": "Teams with a home-nation manager reached the top four 22.7% of the time and won all 21 titles; teams with a foreign manager reached the top four only 7.1% of the time and never won. This is a correlation, not a cause: strong football nations usually appoint their own coaches, while foreign coaches are more often hired by less established teams.",
"Q29": "Only 4 of the 11 Golden Ball winners came from the champion team (1978, 1982, 1986, 1994). Since 1998 the award has always gone to a player from a beaten team, usually the runner-up. The award recognises individual performance more than team success.",
"Q30": "The 2,548 goal rows reproduce all 1,800 team-match scores exactly, with no mismatches and no goal attached to a team that was not in the match. The load was complete and consistent, so every goal-based query above can be trusted.",
}
